project:
  type: website
  output-dir: docs

website:
  title: "Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Tests
        href: slides/cm_intro.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
